apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feed-services
  name: service-feeds
spec:
  ports:
  - name: service-feeds
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-feeds
